-- Crear la base de datos
CREATE DATABASE MiniMarket;
GO

USE MiniMarket;
GO

-- tabla de categorias
CREATE TABLE CATEGORIES (
    CATEGORY_ID INT PRIMARY KEY IDENTITY(1,1),
    NAME NVARCHAR(50) NOT NULL,
    DESCRIPTION NVARCHAR(200) NULL,
    CREATION_DATE DATETIME DEFAULT GETDATE(),
	MODIFICATION_DATE DATETIME DEFAULT GETDATE(),
    STATUS NVARCHAR(1) DEFAULT 'R' NOT NULL,
);
GO

CREATE TABLE PROVINCES (
	PROVINCE_ID INT PRIMARY KEY IDENTITY(1, 1),
	NAME NVARCHAR(100) NOT NULL
);
GO

-- tabla de proveedores
CREATE TABLE SUPPLIERS (
    SUPPLIER_ID INT PRIMARY KEY IDENTITY(1,1),
    NAME NVARCHAR(100) NOT NULL,
    ADDRESS NVARCHAR(200) NULL,
    PHONE NVARCHAR(20) NULL,
    EMAIL NVARCHAR(100) NULL,
	PROVINCE_ID INT NULL,
    CREATION_DATE DATETIME DEFAULT GETDATE(),
	MODIFICATION_DATE DATETIME DEFAULT GETDATE(),
    STATUS NVARCHAR(1) DEFAULT 'R' NOT NULL,
	FOREIGN KEY (PROVINCE_ID) REFERENCES PROVINCES(PROVINCE_ID),
);
GO

-- tabla de productos
CREATE TABLE PRODUCTS (
    PRODUCT_ID INT PRIMARY KEY IDENTITY(1,1),
    NAME NVARCHAR(100) NOT NULL,
    DESCRIPTION NVARCHAR(500) NULL,
    PRICE DECIMAL(10, 2) NOT NULL,
    STOCK INT NOT NULL DEFAULT 0,
    CATEGORY_ID INT NOT NULL,
    SUPPLIER_ID INT NOT NULL,
    CREATION_DATE DATETIME DEFAULT GETDATE(),
    MODIFICATION_DATE DATETIME DEFAULT GETDATE(),
    EXPIRATION_DATE DATE NULL,
    STATUS NVARCHAR(1) DEFAULT 'R' NOT NULL,
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(CATEGORY_ID),
    FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIERS(SUPPLIER_ID)
);
GO

-- tabla de Clientes
CREATE TABLE CUSTOMERS (
    CUSTOMER_ID INT PRIMARY KEY IDENTITY(1,1),
    NAME NVARCHAR(100) NOT NULL,
    LAST_NAME NVARCHAR(100) NOT NULL,
	BIRTHDATE DATETIME,
    EMAIL NVARCHAR(100) NULL,
    PHONE NVARCHAR(20) NULL,
    ADDRESS NVARCHAR(200) NULL,
	PROVINCE_ID INT NULL,
    CREATION_DATE DATETIME DEFAULT GETDATE(),
	MODIFICATION_DATE DATETIME DEFAULT GETDATE(),
    STATUS NVARCHAR(1) DEFAULT 'R' NOT NULL,
	FOREIGN KEY (PROVINCE_ID) REFERENCES PROVINCES(PROVINCE_ID),
);
GO

-- tabla de ventas
CREATE TABLE SALES (
    SALE_ID INT PRIMARY KEY IDENTITY(1,1),
    CUSTOMER_ID INT NOT NULL,
    SALE_DATE DATETIME NOT NULL DEFAULT GETDATE(),
    TOTAL DECIMAL(10, 2) NOT NULL,
	CREATION_DATE DATETIME DEFAULT GETDATE(),
	MODIFICATION_DATE DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID),
	STATUS NVARCHAR(1) DEFAULT 'R' NOT NULL,
);
GO

-- tabla de detalles de venta
CREATE TABLE SALES_DETAILS (
    DETAIL_ID INT PRIMARY KEY IDENTITY(1,1),
    SALE_ID INT NOT NULL,
    PRODUCT_ID INT NOT NULL,
    AMOUNT INT NOT NULL,
    UNIT_PRICE DECIMAL(10, 2) NOT NULL,
    SUBTOTAL DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (SALE_ID) REFERENCES SALES(SALE_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
);
GO
